version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/l-store-app
      - public-data:/l-store-app/public
      - tmp-data:/l-store-app/tmp
      - log-data:/l-store-app/log
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: 'db'
    ports:
    - '127.0.0.1:8080:80'
  db:
    container_name: mysql
    image: mysql:5.7
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  l-store-app:
    build:
      context: containers/nginx
    volumes:
      - public-data:/l-store-app/public
      - tmp-data:/l-store-app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: